// Auto-generated by scripts/prepare-visuals.js - Do not edit manually
export const visualFiles = [
  "whatsapp-image-2026-09-30-at-13-50-33-1.jpeg",
  "whatsapp-image-2026-09-30-at-13-50-33.jpeg",
  "1.png",
  "2.jpg",
  "visuel-1.jpg",
  "visuel-2.jpg",
  "visuel-3.jpg",
  "visuel-4.jpg",
  "visuel-5.jpg",
  "visuel-6.jpg",
  "visuel-7.jpg",
  "visuel-8.jpg",
  "visuel-10.jpg",
  "visuel-11.jpg",
  "visuel-12.jpg",
  "visuel-13.jpg",
  "visuel-15.jpg",
  "visuel-16.jpg",
  "visuel-17.jpg",
  "visuel-19.jpg"
];
